GET  http://localhost:3000/dev/posts
Content-Type: application/json;
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9qZWN0cyI6W3sicHJvamVjdCI6ImEiLCJyb2wiOiJhIn0seyJwcm9qZWN0IjoiYiIsInJvbCI6ImIifV0sImlhdCI6MTcyODMyMTE4MywiZXhwIjoxNzI4MzI0NzgzfQ.QA_RddVvUCNu3S3pWrRz7f_wgo2X_5Fo3Nq_stSB9VA